"use client";

import {
  getGradeLevelLabel,
  philIriPhaseLabel,
  PHILIRI_QUESTION_TYPES,
  PHILIRI_QUESTION_TYPE_ABBR,
} from "@/lib/constants";
import { Check, X } from "lucide-react";
import type { PhilIriIsrRow } from "../philiriUtils";

interface Props {
  language: string;
  phase: string;
  rows: PhilIriIsrRow[];
}

/**
 * On-screen Individual Summary Record (Phil-IRI Form 4 / ISR — Talaan ng
 * Indibidwal na Pagbabasa). Summary of comprehension responses per passage
 * level, derived from the learner's recorded passage reads. Read-only; the
 * printable version is generated by generatePhilIriIsr.
 */
export function PhilIriIsrSummary({ language, phase, rows }: Props) {
  // The passage with the most questions sets the number of response columns.
  const maxQuestions = rows.reduce(
    (m, r) => Math.max(m, r.answers.length),
    0,
  );
  const questionCols = Array.from({ length: maxQuestions }, (_, i) => i);
  // Pre-Test at Beginning of School Year; Post Test at End of School Year.
  const isPre = phase === "BoSY";
  const isPost = phase === "EoSY";

  const cell = (correct: boolean | null | undefined) => {
    if (correct === true)
      return <Check className="mx-auto h-3.5 w-3.5 text-green-700" />;
    if (correct === false)
      return <X className="mx-auto h-3.5 w-3.5 text-red-700" />;
    return <span className="text-muted-foreground">·</span>;
  };

  return (
    <div className="space-y-2 border-t pt-4">
      <div>
        <p className="text-sm font-semibold">
          Individual Summary Record (ISR)
        </p>
        <p className="text-xs italic text-muted-foreground">
          Talaan ng Indibidwal na Pagbabasa (TIP) — Summary of Comprehension
          Responses
        </p>
      </div>
      <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">
        <span>
          Language: <span className="font-medium text-foreground">{language}</span>
        </span>
        <span>
          {isPre ? "☑" : "☐"} Pre-Test&nbsp;&nbsp;{isPost ? "☑" : "☐"} Post Test
          <span className="ml-1">({philIriPhaseLabel(phase)})</span>
        </span>
      </div>
      <div className="overflow-x-auto rounded-md border">
        <table className="min-w-full border-collapse text-sm">
          <thead>
            <tr className="bg-muted/60">
              <th rowSpan={2} className="border px-2 py-1.5 text-left">
                Passage Level
              </th>
              <th
                colSpan={Math.max(questionCols.length, 1)}
                className="border px-2 py-1 text-center"
              >
                Responses to Questions
              </th>
              <th rowSpan={2} className="border px-2 py-1.5 text-center">
                Score per Type of Question
              </th>
              <th rowSpan={2} className="border px-2 py-1.5 text-center">
                Score
              </th>
              <th rowSpan={2} className="border px-2 py-1.5 text-center">
                %
              </th>
              <th rowSpan={2} className="border px-2 py-1.5 text-center">
                Reading Level
              </th>
            </tr>
            <tr className="bg-muted/60">
              {questionCols.map((i) => (
                <th
                  key={i}
                  className="border px-1.5 py-1 text-center text-[11px]"
                >
                  Q{i + 1}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((r, idx) => (
              <tr key={idx} className="hover:bg-muted/30">
                <td className="border px-2 py-1 whitespace-nowrap font-medium">
                  {getGradeLevelLabel(r.grade)}
                </td>
                {questionCols.map((i) => (
                  <td key={i} className="border px-1.5 py-1 text-center">
                    {cell(r.answers[i]?.correct)}
                  </td>
                ))}
                <td className="border px-2 py-1 text-center text-[11px] whitespace-nowrap">
                  {PHILIRI_QUESTION_TYPES.map((t) => (
                    <span key={t} className="mr-1.5 inline-block">
                      {PHILIRI_QUESTION_TYPE_ABBR[t]}={r.byType[t].correct}/
                      {r.byType[t].total}
                    </span>
                  ))}
                </td>
                <td className="border px-2 py-1 text-center font-semibold whitespace-nowrap">
                  {r.rawCorrect}/{r.totalQuestions}
                </td>
                <td className="border px-2 py-1 text-center">
                  {r.comprehensionScore === null ? "-" : r.comprehensionScore}
                </td>
                <td className="border px-2 py-1 text-center text-xs font-medium">
                  {r.readingLevel ?? "-"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-[11px] text-muted-foreground">
        <span className="font-medium">Legend:</span> L — Literal; I —
        Inferential; C — Critical
      </p>
    </div>
  );
}
