#!/usr/bin/env bash
# PreToolUse(Bash) guard — see CLAUDE.md / AGENTS.md RULE 0.
#
# All work happens on the LOCAL Supabase clone. Production holds real DepEd
# learner records and must never be read or written by any agent or script.
#
#   hosted Supabase host, .env.local, linking, remote db commands -> deny
#   psql whose every connection target is local — or none at all,
#     which is libpq's Unix socket on this machine                -> allow (no prompt)
#   psql naming a host that cannot be shown to be local           -> ask
#   everything else                                               -> fall through
#
# Heredoc bodies are stripped before matching: `cat > doc.md <<'EOF' ... EOF`
# is writing text *about* production, not connecting to it. That also means a
# script written through a heredoc is not inspected — this hook is a backstop
# for the rules in RULE 0, not a sandbox. A deny is the rule working: do not
# rephrase the command to slip past it and do not edit this file to get a task
# done; say so and let the user decide.
#
# What section 4 cannot see, both consequences of reading one command line in
# isolation: a host that arrives through a shell variable (`psql "$SOME_URL"`)
# or through a PGHOST exported by the user's profile. Those are judged local on
# the strength of libpq's default, deliberately — prompting on every command
# containing the letters "psql" is what teaches a user to click through the
# prompt that matters. Sections 1-3 still scan the whole line, so a hosted
# Supabase host is denied wherever on it it appears.

input=$(cat)
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

decide() {
  jq -nc --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:$d,permissionDecisionReason:$r}}'
  exit 0
}

# Drop the body of every heredoc, keeping the command lines themselves.
scan=$(printf '%s\n' "$cmd" | awk '
  BEGIN { tag = "" }
  {
    if (tag != "") {
      line = $0
      gsub(/^[ \t]+|[ \t]+$/, "", line)
      if (line == tag) tag = ""
      next
    }
    if (match($0, /<<-?[ \t]*["\x27]?[A-Za-z_][A-Za-z0-9_]*/)) {
      t = substr($0, RSTART, RLENGTH)
      sub(/^<<-?[ \t]*/, "", t)
      gsub(/["\x27]/, "", t)
      tag = t
    }
    print
  }')

LOCAL_DB='postgresql://postgres:postgres@127.0.0.1:54322/postgres'

# 1. A hosted Supabase endpoint (db.<ref>.supabase.co, <ref>.supabase.co,
#    aws-*.pooler.supabase.com). Note "https://supabase.com/docs" has no dot
#    before "supabase" and is therefore not matched.
if printf '%s' "$scan" | grep -Eqi '\.supabase\.(co|com|in)\b'; then
  decide deny "That is a hosted Supabase host — production DepEd learner records. RULE 0: local only ($LOCAL_DB). Do not retry against production."
fi

# 2. The live credentials file. Never read, printed, copied, or passed to a
#    script. (`npm run build` reads it internally and is unaffected.)
if printf '%s' "$scan" | grep -Eq '\.env\.local\b'; then
  decide deny ".env.local holds LIVE production credentials — RULE 0 forbids reading or sourcing it. Use .env.development.local (local clone)."
fi

# 3. Linking the CLI to the remote project, or any command that acts on it.
if printf '%s' "$scan" | grep -Eq 'supabase[[:space:]]+link|--linked|db[[:space:]]+(push|pull|remote)|--project-ref'; then
  decide deny "The project is deliberately unlinked (linked_project: null) so no CLI command can reach production. RULE 0: leave it that way."
fi

# 4. psql. The only question is whether it can reach production, and the
#    connection target answers it. A hosted Supabase host never arrives here:
#    section 1 denied it already.
#
#    `psql` has to appear as a COMMAND, not as a substring — `grep -r "psql"
#    docs/`, a commit message and this file's own comments are not connections.
if printf '%s' "$scan" | grep -Eq '(^|[;|&(]|[[:space:]])([A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*[[:space:]]+)*psql([[:space:]]|$)'; then

  # Every connection target named on the line, one per output line. A bare
  # host, a PG* assignment, a keyword/value conninfo and a URI all count;
  # "service" stands for a target only ~/.pg_service.conf could resolve.
  targets=$(printf '%s\n' "$scan" | awk '
    function emit(h) { if (h != "") print tolower(h) }
    function uri_host(t,   s, a) {
      sub(/^[a-z]+:\/\//, "", t)
      s = t
      sub(/[\/?].*$/, "", s)          # authority only
      a = s
      sub(/^.*@/, "", a)              # drop any user:password
      sub(/:[0-9]*$/, "", a)          # drop the port
      return a
    }
    {
      line = $0
      gsub(/[;|&()]/, " ", line)
      gsub(/["\x27]/, "", line)
      n = split(line, tok, /[ \t]+/)
      for (i = 1; i <= n; i++) {
        t = tok[i]
        # A conninfo passed as the database: `--dbname=<uri>`, `-d<uri>`.
        if (t ~ /^--dbname=/) sub(/^--dbname=/, "", t)
        else if (t ~ /^-d.+/) sub(/^-d/, "", t)
        if (t ~ /^([Pp][Gg][Ss][Ee][Rr][Vv][Ii][Cc][Ee]=|service=)/) { emit("service"); continue }
        if (t ~ /^postgres(ql)?:\/\//)   { emit(uri_host(t)); continue }
        if (t ~ /^(PGHOSTADDR|PGHOST)=/) { sub(/^[^=]*=/, "", t); emit(t); continue }
        if (t ~ /^host=/)                { sub(/^host=/, "", t); emit(t); continue }
        if (t ~ /^--host=/)              { sub(/^--host=/, "", t); emit(t); continue }
        if (t == "-h" || t == "--host")  { emit(tok[i+1]); i++; continue }
        if (t ~ /^-h.+/)                 { sub(/^-h/, "", t); emit(t); continue }
      }
    }')

  if [ -z "$targets" ]; then
    decide allow "psql with no host argument — libpq connects over the local Unix socket, which cannot reach production."
  fi

  # Loopback, or a Unix socket directory (an absolute path).
  remote=$(printf '%s\n' "$targets" | grep -Ev '^(127\.0\.0\.1|localhost|::1|/.*)$')
  if [ -z "$remote" ]; then
    decide allow "psql against the local Supabase clone."
  fi

  first=$(printf '%s\n' "$remote" | head -1)
  if [ "$first" = "service" ]; then
    decide ask "psql through a connection service file — its host comes from ~/.pg_service.conf and cannot be checked here. Confirm it is the local clone ($LOCAL_DB)."
  fi
  decide ask "psql names the host '$first', which is not the local clone. Confirm it cannot reach production ($LOCAL_DB)."
fi

exit 0
