#!/usr/bin/env bash
# PreToolUse(Bash) guard — see CLAUDE.md / AGENTS.md RULE 0.
#
# All work happens on the LOCAL Supabase clone. Production holds real DepEd
# learner records and must never be read or written by any agent or script.
#
#   hosted Supabase host, .env.local, linking, remote db commands -> deny
#   psql against explicit 127.0.0.1|localhost                     -> allow (no prompt)
#   psql with no explicit host                                    -> ask
#   everything else                                               -> fall through
#
# Heredoc bodies are stripped before matching: `cat > doc.md <<'EOF' ... EOF`
# is writing text *about* production, not connecting to it. That also means a
# script written through a heredoc is not inspected — this hook is a backstop
# for the rules in RULE 0, not a sandbox. A deny is the rule working: do not
# rephrase the command to slip past it and do not edit this file to get a task
# done; say so and let the user decide.

input=$(cat)
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

decide() {
  jq -nc --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:$d,permissionDecisionReason:$r}}'
  exit 0
}

# Drop the body of every heredoc, keeping the command lines themselves.
scan=$(printf '%s\n' "$cmd" | awk '
  BEGIN { tag = "" }
  {
    if (tag != "") {
      line = $0
      gsub(/^[ \t]+|[ \t]+$/, "", line)
      if (line == tag) tag = ""
      next
    }
    if (match($0, /<<-?[ \t]*["\x27]?[A-Za-z_][A-Za-z0-9_]*/)) {
      t = substr($0, RSTART, RLENGTH)
      sub(/^<<-?[ \t]*/, "", t)
      gsub(/["\x27]/, "", t)
      tag = t
    }
    print
  }')

LOCAL_DB='postgresql://postgres:postgres@127.0.0.1:54322/postgres'

# 1. A hosted Supabase endpoint (db.<ref>.supabase.co, <ref>.supabase.co,
#    aws-*.pooler.supabase.com). Note "https://supabase.com/docs" has no dot
#    before "supabase" and is therefore not matched.
if printf '%s' "$scan" | grep -Eqi '\.supabase\.(co|com|in)\b'; then
  decide deny "That is a hosted Supabase host — production DepEd learner records. RULE 0: local only ($LOCAL_DB). Do not retry against production."
fi

# 2. The live credentials file. Never read, printed, copied, or passed to a
#    script. (`npm run build` reads it internally and is unaffected.)
if printf '%s' "$scan" | grep -Eq '\.env\.local\b'; then
  decide deny ".env.local holds LIVE production credentials — RULE 0 forbids reading or sourcing it. Use .env.development.local (local clone)."
fi

# 3. Linking the CLI to the remote project, or any command that acts on it.
if printf '%s' "$scan" | grep -Eq 'supabase[[:space:]]+link|--linked|db[[:space:]]+(push|pull|remote)|--project-ref'; then
  decide deny "The project is deliberately unlinked (linked_project: null) so no CLI command can reach production. RULE 0: leave it that way."
fi

# 4. psql keeps its original behaviour: local is allowed outright, anything
#    ambiguous is confirmed with the user.
case "$scan" in
  *psql*)
    if printf '%s' "$scan" | grep -Eq '127\.0\.0\.1|localhost'; then
      decide allow "psql against the local Supabase clone."
    fi
    decide ask "psql with no explicit local host — confirm it cannot reach production."
    ;;
esac

exit 0
