-- ============================================================================
-- Student Portal access code
-- ============================================================================
-- Students sign in to the Student Portal with their LRN + a portal code
-- (replacing date of birth). The code is system-generated when the section
-- adviser clicks "Generate Code" on the student details modal, and handed to
-- the learner. Stored in plaintext (same trust level as the previous DOB
-- check); LRN remains the unique identifier.
-- ============================================================================

ALTER TABLE procurements.sms_students
  ADD COLUMN IF NOT EXISTS portal_code TEXT;

COMMENT ON COLUMN procurements.sms_students.portal_code IS
  'System-generated Student Portal access code (LRN + code sign-in). Generated by the section adviser from the student details modal.';
